name: VPN
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-18.04
    timeout-minutes: 9999

    steps:

    - name: Install Rclone
      run: sudo apt-get install screen git && curl https://rclone.org/install.sh | sudo bash
      
    - name: Rclone config
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}      
